global__input.A.0 0
global__input.A.1 1
global__input.A.2 2
global__input.A.3 3
global__input.A.4 4
global__input.A.5 5
global__input.A.6 6
global__input.A.7 7
global__input.A.8 8
global__input.A.9 9
global__input.B.0 0
global__input.B.1 1
global__input.B.2 2
global__input.B.3 3
global__input.B.4 4
global__input.B.5 5
global__input.B.6 6
global__input.B.7 7
global__input.B.8 8
global__input.B.9 9
